// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/aidapedia/jabberwock/internal/interface/http"
	"github.com/aidapedia/jabberwock/internal/interface/http/handler"
	"github.com/aidapedia/jabberwock/internal/repository/session"
	"github.com/aidapedia/jabberwock/internal/repository/user"
	"github.com/aidapedia/jabberwock/internal/usecase/authenticated"
)

// Injectors from wire.go:

func InitHTTPServer(ctx context.Context) http.HTTPServiceInterface {
	db := databaseProvider(ctx)
	engineInterface := redisProvider(ctx)
	sessionInterface := session.New(db, engineInterface)
	userInterface := user.New()
	enforcer := casbinProvider(ctx)
	authenticatedInterface := authenticated.New(sessionInterface, userInterface, enforcer)
	handlerHandler := handler.NewHandler(authenticatedInterface)
	httpServiceInterface := http.NewHTTPService(handlerHandler)
	return httpServiceInterface
}
