// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/aidapedia/jabberwock/internal/interface/http"
)

// Injectors from wire.go:

func InitHTTPServer() http.HTTPServiceInterface {
	httpServiceInterface := http.NewHTTPService()
	return httpServiceInterface
}
